### ISSUE TITLE
Trying to submit with Firefox: error processing file, undefined method `[]' for nil:NilClass

### ISSUE THREAD

**Issue by Mat2095** [autolab/Autolab#1134]
I'm trying to submit a file on the demo-site using firefox.

I can drag the file in and the file-info is correct.
But when I check the "I affirm..."-checkbox, the file disappears and an error is shown which says "There was an error processing your file, please try again."

Then I can drag the file in again and click submit.
This however results in an error-page:

![ClipboarderTemp-2673619](https://user-images.githubusercontent.com/11258252/80253408-8512fb80-8679-11ea-9f44-826559b30e0b.png)

This happened on two machines (windows and linux) using Firefox, while Chrome works fine.

**Comment by victorhuangwq** [comment]
Hi @Mat2095 that does look like something we should look into. I have however just tested the demo site on firefox, with a tar file and it still seemed to work fine. May I know what kind of file did you try to submit? I suspect that the filetype / the file itself could be relevant to the issue this time around.

**Comment by Mat2095** [comment]
Okay, I guess I did get a few things wrong.
I submitted to the Lab Template, which doesn't really work even on Chrome (make doesn't find the python command, so everything just fails).
So I added the hello-lab, which works fine on Chrome (score of 100 when submitting the hello.c solution file).

Doing the same thing fails on firefox (hello.c from https://github.com/autolab/Autolab/blob/master/examples/hello/src/hello.c ).
However I've noticed that the error doesn't occur every time. If I Ctrl+F5 reload on http://autolab.ml/courses/AutoPopulated/assessments/hello drag-in the file and check the checkbox, the error occurs in about 50% of the cases.
If I click the upload-region to select a file, I didn't get the error (tried it about 10 times).

**Comment by cg2v** [comment]
Note that the CMU instance has had this problem in the past:
https://lists.andrew.cmu.edu/mailman/private/autolab-dev/2018-May/044484.html  (devs only)
It's patched there now:
https://github.com/cg2v/Autolab/commit/df5e132d63eb25dade8911329ffb2cc777da4baa

**Comment by fanpu** [comment]
Closing because fix has been merged in #1138

**Comment by Mat2095** [comment]
Now there is a nice error message "Submission was blank - please upload again".
But the bug that (sometimes, with firefox) caused the blank submission in the first place is still present!

**Comment by fanpu** [comment]
Hey @Mat2095, sorry about that - could I check which version of Firefox you are on, and whether you have tried this with all extensions disabled? I could not replicate this issue on Firefox 74.0.1 on Linux after submitting 5 times

**Comment by Mat2095** [comment]
For me this error occurs on a Ubuntu 18.04 VM where nothing besides Autolab is installed. Firefox is on version 76.0 with no addons. But it also happens on my Windows PC using Firefox 76.0.1 on the http://autolab.ml site.

I've recorded a small video: https://www.youtube.com/watch?v=ZKMTDuvKRAI
First I just reload the page. I drag in the file, the content seems to get read successfully (LoC is correct). But when I check the checkbox, an error occurs. Then I drag in the file again and submit, resulting in the "Submission was blank"-error. Finally I upload via the upload-dialog, which works without a problem.

**Comment by fanpu** [comment]
Thanks for the recording, I will try to replicate the issue on Windows using your setup

**Comment by damianhxy** [comment]
For `showFiles` to be called from `dropHandler`, we must have `fileSelector.files.length === 1`.

However, for the error to display when `#integrity_checkbox` changes, in `enableSubmit`, we must have `fileSelector.files.length === 0`.

So somehow, the length is changing between the drag-and-drop, and the checking of the checkbox. But this should not happen since `fileSelector.files` is only cleared when `#remove-handed-in` is clicked.

It would be great if the root cause can be identified, but I'll close this issue as can't repro for now.
