### ISSUE TITLE
Roster import should not fail on duplicate email addresses

### ISSUE THREAD

**Issue by TheodorJ** [autolab/Autolab#906]
Any fatal duplicates should be caught and presented to the user for cherry-picking. I described this more in #581.

**Comment by victorhuangwq** [comment]
The issue should be addressed in the new roster import upgrade.

**Comment by damianhxy** [comment]
Issue is partially addressed. When too many duplicates exist, we get a cookie overflow error instead

**Comment by damianhxy** [comment]
For reference: https://stackoverflow.com/questions/9473808/cookie-overflow-in-rails-application

**Comment by damianhxy** [comment]
![Screenshot 2023-03-13 at 00 12 01](https://user-images.githubusercontent.com/9074856/224606519-2e5e81d1-a473-4946-ba89-050b9d74cea9.png)

Could be worth considering switching to a non-flash based approach (just like bulk upload grades).
